modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="slothcraft"
version="1.0.0"
displayName="SlothCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MasterSloth, MCreator"

[[dependencies.slothcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



